FROM golang:1.24-alpine AS builder

WORKDIR /app


COPY . .


RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -o client ./cmd/client


FROM alpine:latest

WORKDIR /app


RUN mkdir -p config


COPY --from=builder /app/client .
COPY --from=builder /app/config/config.json ./config/config.json

# Запускаем клиент
CMD ["./client"] 